### ISSUE TITLE
The  code  for slice animation was written in 2017

### ISSUE THREAD

**Issue by empet** [LukeBlueLOx/Dash#1]
These lines of code [https://plotly.com/python/visualizing-mri-volume-slices/](https://plotly.com/python/visualizing-mri-volume-slices/) have been written in Oct 3, 2017. It was an experimental code, with particular data (the number of slices is 68, and all the code is written around this number)., which should be removed from the list of Plotly tutorials. There is  a more general approach here:  [https://nbviewer.org/github/empet/Animating-MRI-scans/blob/master/scanning-the-head-classic.ipynb](https://nbviewer.org/github/empet/Animating-MRI-scans/blob/master/scanning-the-head-classic.ipynb).
There is  also a Julia version: 
[https://discourse.julialang.org/t/plotlyjs-jl-animation/70058/3](https://discourse.julialang.org/t/plotlyjs-animation/70058/3).
and oblique slices, generated by PlotlyJS.jl: 
![oblique-slices](https://user-images.githubusercontent.com/3627253/210758879-ab04298c-3156-4526-9fab-e813c50185a9.gif)
Hence what are the novelties in the dash app? htm+css   :).

**Comment by LukeBlueLOx** [comment]
@empet 
Why have I not seen a notification anywhere that the creator of this wonderful visualization is sending me valuable tips? 🙂.  I've been struggling with the map for Poland created with Dash all day and I think I'll find a solution tomorrow 👍.  That's why I saw Your tips so late - sorry 👍🍀☀️🙂✌.

**Comment by LukeBlueLOx** [comment]
@empet 
P.S. I added Your valuable tips to the readme file in my Dash repository 👍🍀☀️🙂✌. If there is someone willing with their own set of MRI images or x-rays - then I will try to adjust the parameters of the code for the individual case.  But in my free time I will also explore the topic according to Your tips - thank You 👍🍀☀️🙂✌.

**Comment by empet** [comment]
I suggest to scan the MRI images with html&css, not exploiting the someone else ideas.

**Comment by LukeBlueLOx** [comment]
@empet 
OK, thanks👍✌:
https://www.linkedin.com/posts/lukebluelox_plotly-dash-python-activity-7016004370542563328-pF8y?utm_source=share&utm_medium=member_android
I will direct everyone interested to You. And You don't even have to thank me for free promotion and advertising.  Though it also cost me some work and time - and it's not only just html and css.
It's good that Poles do not prohibited using their ideas - because people would not have liquid oxygen in hospitals when they were suffering from COVID and Elon Musk would have to use something else for his rockets.
https://blox-land.herokuapp.com
✌💙💚♻️🌌🚀🌎🌍🌏🛰🌌♻️💚💙✌

**Comment by LukeBlueLOx** [comment]
<div align="center">
<img width="50%" src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?username=LukeBlueLOx&theme=github_dark&layout=compact&langs_count=7"/>

https://github.com/anuraghazra/github-readme-stats
</div>
